import * as i0 from '@angular/core';
import { EventEmitter, OnDestroy } from '@angular/core';
import { FormControl } from '@angular/forms';
import * as rxjs from 'rxjs';
import { Subject, Observable, Subscription } from 'rxjs';
import { Router, CanActivate } from '@angular/router';
import { CookieService } from 'ngx-cookie-service';
import { HttpHeaders, HttpClient, HttpResponse, HttpEvent } from '@angular/common/http';
import { MatDialogRef, MatDialog } from '@angular/material/dialog';
import * as _angular_material_dialog_d from '@angular/material/dialog.d';

declare class FfsjWebComponentsComponent {
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjWebComponentsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FfsjWebComponentsComponent, "lib-ffsj-web-components", never, {}, {}, never, never, true, never>;
}

declare class FfsjWebComponentsService {
    constructor();
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjWebComponentsService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<FfsjWebComponentsService>;
}

declare enum AlertType {
    Success = "success",
    Danger = "danger",
    Warning = "warning",
    Info = "info"
}

declare class FfsjAlertService {
    alert$: Subject<{
        type: AlertType;
        message: string;
        duration: number;
    }>;
    success(message: string, duration?: number): void;
    danger(message: string, duration?: number): void;
    warning(message: string, duration?: number): void;
    info(message: string, duration?: number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjAlertService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<FfsjAlertService>;
}

interface ConfigurationParameters {
    apiKeys?: {
        [key: string]: string;
    };
    username?: string;
    password?: string;
    accessToken?: string | (() => string);
    basePath?: string;
    withCredentials?: boolean;
}
declare class Configuration {
    apiKeys?: {
        [key: string]: string;
    };
    username?: string;
    password?: string;
    accessToken?: string | (() => string);
    basePath?: string;
    withCredentials?: boolean;
    constructor(configurationParameters?: ConfigurationParameters);
    /**
     * Select the correct content-type to use for a request.
     * Uses {@link Configuration#isJsonMime} to determine the correct content-type.
     * If no content type is found return the first found type if the contentTypes is not empty
     * @param contentTypes - the array of content types that are available for selection
     * @returns the selected content-type or <code>undefined</code> if no selection could be made.
     */
    selectHeaderContentType(contentTypes: string[]): string | undefined;
    /**
     * Select the correct accept content-type to use for a request.
     * Uses {@link Configuration#isJsonMime} to determine the correct accept content-type.
     * If no content type is found return the first found type if the contentTypes is not empty
     * @param accepts - the array of content types that are available for selection.
     * @returns the selected content-type or <code>undefined</code> if no selection could be made.
     */
    selectHeaderAccept(accepts: string[]): string | undefined;
    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    isJsonMime(mime: string): boolean;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
interface Asociacion {
    [key: string]: any;
    /**
     * Identificador único de la asociación.
     */
    id: number;
    /**
     * Nombre de la asociación.
     */
    nombre: string;
    /**
     * CIF de la asociación.
     */
    cif: string;
    /**
     * Dirección postal de la asociación.
     */
    direccion?: string;
    /**
     * Lema de la asociación.
     */
    lema?: string;
    /**
     * Año de fundación de la asociación.
     */
    anyoFundacion?: number;
    /**
     * Correo electrónico de contacto de la asociación.
     */
    email: string;
    /**
     * Contraseña de acceso al sistema para la asociación.
     */
    password?: string;
    /**
     * Número de teléfono de contacto de la asociación.
     */
    telefono?: string;
    /**
     * Código numérico que representa el tipo de asociación.
     */
    tipoAsociacion: number;
    /**
     * Indica si el componente está activo o no.
     */
    active?: number;
    /**
     * Imagen que tiene la asociación.
     */
    img?: string;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
interface Status {
    /**
     * Estado en la que acaba la llamada
     */
    status?: number;
    /**
     * Mensaje que describe el estatus que se ha puesto
     */
    message?: string;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

interface ResponseAsociaciones {
    [key: string]: any;
    asociaciones?: Array<Asociacion>;
    status?: Status;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
interface Asociado {
    [key: string]: any;
    /**
     * Identificador del asociado
     */
    id: number;
    /**
     * NIF del usuario, consiste en 8 dígitos seguidos de una letra mayúscula.
     */
    nif: string;
    /**
     * Nombre del usuario.
     */
    nombre: string;
    /**
     * Apellidos del usuario.
     */
    apellidos: string;
    /**
     * Número de teléfono del usuario.
     */
    telefono: string;
    /**
     * Correo electrónico del usuario.
     */
    email: string;
    /**
     * Contraseña del usuario.
     */
    password?: string;
    /**
     * Dirección postal del usuario.
     */
    direccion?: string;
    /**
     * Código postal de la dirección del usuario.
     */
    codigoPostal?: string;
    /**
     * Fecha de nacimiento del usuario en formato YYYY-MM-DD.
     */
    fechaNacimiento?: string;
    /**
     * Indica si el componente está activo o no.
     */
    active?: number;
    /**
     * Imagen que tiene la asociado.
     */
    img?: string;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

interface ResponseAsociados {
    [key: string]: any;
    asociados?: Array<Asociado>;
    status?: Status;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Token
 */
type Token = string;

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

interface ResponseToken {
    [key: string]: any;
    token?: Token;
    status?: Status;
}

/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
interface Usuario {
    /**
     * Usuario para realizar el login
     */
    user: string;
    /**
     * Contraseña para realizar el login
     */
    password: string;
}

declare class CensoService {
    private httpClient;
    protected basePath: string;
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    constructor(httpClient: HttpClient);
    /**
     * Listar todas las asociaciones
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    asociacionesGet(observe?: 'body', reportProgress?: boolean): Observable<ResponseAsociaciones>;
    asociacionesGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseAsociaciones>>;
    asociacionesGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseAsociaciones>>;
    /**
     * Realizar la autentificación del usuario
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    doLogin(body: Usuario, observe?: 'body', reportProgress?: boolean): Observable<ResponseToken>;
    doLogin(body: Usuario, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseToken>>;
    doLogin(body: Usuario, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseToken>>;
    /**
   * Obtener un asociado
   *
   * @param asociado
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
    asociadosGetById(asociado: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseAsociados>;
    asociadosGetById(asociado: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseAsociados>>;
    asociadosGetById(asociado: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseAsociados>>;
    /**
* Actualizar un asociado
*
* @param body
* @param asociado
* @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
* @param reportProgress flag to report request and response progress.
*/
    asociadosPut(body: ResponseAsociados, asociado: number, observe?: 'body', reportProgress?: boolean): Observable<ResponseAsociados>;
    asociadosPut(body: ResponseAsociados, asociado: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResponseAsociados>>;
    asociadosPut(body: ResponseAsociados, asociado: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResponseAsociados>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<CensoService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<CensoService>;
}

declare class EncoderService {
    private key;
    private iv;
    constructor();
    encryptPassword(data: string): string;
    checkPassword(password: string, encrypted: string): boolean;
    encrypt(password: string): string;
    decrypt(passwordToDecrypt: string): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<EncoderService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EncoderService>;
}

declare class AuthService {
    private router;
    private censoService;
    private encoderService;
    private cookieService;
    private loginStatus$;
    loginStatusObservable: rxjs.Observable<boolean>;
    constructor(router: Router, censoService: CensoService, encoderService: EncoderService, cookieService: CookieService);
    checkToken(): boolean;
    checkExpireDateToken(token: string): boolean;
    private isLocalDomain;
    saveToken(token: string): void;
    login(user: string, password: string): Promise<{
        code: number;
        id?: number;
    }>;
    getToken(): string;
    getIdUsuario(): number;
    logout(): void;
    isLoggedIn(): boolean;
    getCargos(): any[];
    updatePassword(asociado: number, password: string): Promise<any>;
    static ɵfac: i0.ɵɵFactoryDeclaration<AuthService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AuthService>;
}

declare class FfsjLoginComponent {
    private authService;
    private alertService;
    title: string;
    subtitle: string;
    logStatus: EventEmitter<boolean>;
    username: FormControl<string | null>;
    password: FormControl<string | null>;
    repeatPassword: FormControl<string | null>;
    loading: boolean;
    showChangePasswordForm: boolean;
    idAsociadoToChangePassword: number;
    constructor(authService: AuthService, alertService: FfsjAlertService);
    ngOnInit(): void;
    login(): Promise<void>;
    changePassword(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjLoginComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FfsjLoginComponent, "lib-ffsj-login", never, { "title": { "alias": "title"; "required": false; }; "subtitle": { "alias": "subtitle"; "required": false; }; }, { "logStatus": "logStatus"; }, never, never, true, never>;
}

declare class AuthGuard implements CanActivate {
    private authService;
    private router;
    private censoService;
    constructor(authService: AuthService, router: Router, censoService: CensoService);
    canActivate(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<AuthGuard, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<AuthGuard>;
}

declare class FfsjSpinnerComponent {
    fullscreen: boolean;
    imagePath: string;
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjSpinnerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FfsjSpinnerComponent, "lib-ffsj-spinner", never, { "fullscreen": { "alias": "fullscreen"; "required": false; }; }, {}, never, never, true, never>;
}

declare class FfsjAlertComponent implements OnDestroy {
    private alertService;
    message: string | null;
    type: AlertType;
    subscription: Subscription;
    constructor(alertService: FfsjAlertService);
    ngOnDestroy(): void;
    closeAlert(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjAlertComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FfsjAlertComponent, "lib-ffsj-alert", never, {}, {}, never, never, true, never>;
}

declare enum AlertButtonType {
    Aceptar = "Aceptar",
    Cancelar = "Cancelar",
    Entendido = "Entendido"
}

interface DataAlert {
    title: string;
    content: string;
    buttonsAlert: AlertButtonType[];
    innerHtml?: string | null;
}
declare class FfsjDialogAlertComponent {
    dialogSelfRef: MatDialogRef<FfsjDialogAlertComponent>;
    data: DataAlert;
    constructor(dialogSelfRef: MatDialogRef<FfsjDialogAlertComponent>, data: DataAlert);
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjDialogAlertComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FfsjDialogAlertComponent, "lib-ffsj-dialog-alert", never, {}, {}, never, never, true, never>;
}

declare class FfsjDialogAlertService {
    private dialog;
    constructor(dialog: MatDialog);
    openDialogAlert(data: DataAlert): _angular_material_dialog_d.MatDialogRef<FfsjDialogAlertComponent, any>;
    static ɵfac: i0.ɵɵFactoryDeclaration<FfsjDialogAlertService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<FfsjDialogAlertService>;
}

export { AlertButtonType, AlertType, AuthGuard, AuthService, EncoderService, FfsjAlertComponent, FfsjAlertService, FfsjDialogAlertComponent, FfsjDialogAlertService, FfsjLoginComponent, FfsjSpinnerComponent, FfsjWebComponentsComponent, FfsjWebComponentsService };
export type { DataAlert };
