import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type AppLanguage = 'es' | 'va' | 'en';

const translations: Record<AppLanguage, Record<string, string>> = {
  es: {
    'language.spanish': 'Castellano', 'language.valencian': 'Valencià', 'language.english': 'English', 'language.label': 'Idioma',
    'nav.home': 'Inicio', 'nav.members': 'Asociados', 'nav.data': 'Datos', 'nav.calendar': 'Calendario', 'nav.registrations': 'Inscripciones', 'nav.forms': 'Formularios', 'nav.exercises': 'Ejercicios', 'nav.record': 'Registro', 'nav.requests': 'Solicitudes', 'nav.permissions': 'Permisos',
    'common.support': 'Soporte', 'common.adminSupport': 'Soporte administrativo', 'common.logout': 'Salir', 'common.close': 'Cerrar', 'common.cancel': 'Cancelar', 'common.loading': 'Cargando...',
    'login.accessAssociations': 'Acceso asociaciones', 'login.title': 'Secretaría FFSJ', 'login.subtitle': 'Acceso para fogueres y barraques.', 'login.help': 'Entra con el CIF de tu asociación y la contraseña facilitada por Secretaría.', 'login.identification': 'Identificación', 'login.enterAssociation': 'Entrar como asociación', 'login.credentialsHelp': 'Usa las credenciales de la entidad, no las de una persona concreta.', 'login.cif': 'CIF de la asociación', 'login.cifPlaceholder': 'Ej. F00000000', 'login.password': 'Contraseña', 'login.entering': 'Entrando...', 'login.forgot': 'No recuerdo la contraseña', 'login.required': 'Introduce el CIF de la asociación y la contraseña.', 'login.failed': 'No hemos podido iniciar sesión. Revisa el CIF y la contraseña.',
    'attachments.select': 'Adjuntar archivo', 'attachments.selected': 'Archivos seleccionados', 'login.adminAccess': 'Soy personal de administración'
    ,'rubi.open': 'Abrir Rubi, asistente virtual', 'rubi.close': 'Cerrar Rubi', 'rubi.name': 'Rubi', 'rubi.you': 'Tu', 'rubi.status': 'Estado', 'rubi.subtitle': 'Tu asistente virtual de Secretaria FFSJ', 'rubi.welcome': 'Hola, soy Rubi, tu asistente virtual de Secretaria FFSJ. En que puedo ayudarte?', 'rubi.quickActions': 'Consultas frecuentes', 'rubi.quick.alta': 'Dar de alta a una persona', 'rubi.quick.documents': 'Enviar documentacion', 'rubi.quick.inscriptions': 'Inscribirme en una actividad', 'rubi.quick.support': 'Tengo un problema', 'rubi.inputLabel': 'Escribe tu consulta a Rubi', 'rubi.placeholder': 'Escribe tu consulta...', 'rubi.send': 'Enviar', 'rubi.loading': 'Rubi esta preparando una respuesta...', 'rubi.disabled': 'Rubi no esta disponible en este momento.', 'rubi.error.auth': 'Tu sesion no permite usar Rubi. Vuelve a iniciar sesion.', 'rubi.error.limit': 'Has alcanzado el limite temporal de consultas. Intentalo de nuevo en unos minutos.', 'rubi.error.disabled': 'Rubi esta deshabilitada temporalmente.', 'rubi.error.unavailable': 'Rubi no esta disponible temporalmente. Intentalo de nuevo mas tarde.', 'rubi.error.timeout': 'Rubi ha tardado demasiado en responder. Puedes volver a intentarlo.', 'rubi.error.invalid': 'No hemos podido procesar la respuesta de Rubi. Puedes volver a intentarlo.', 'rubi.action.personas': 'Ir a Personas', 'rubi.action.registro': 'Ir a Registro', 'rubi.action.inscripciones': 'Abrir Inscripciones', 'rubi.action.soporte': 'Abrir Soporte', 'rubi.action.calendario': 'Abrir Calendario', 'rubi.action.solicitudes': 'Ir a Solicitudes', 'rubi.action.alta': 'Abrir alta de persona'
  },
  va: {
    'language.spanish': 'Castellà', 'language.valencian': 'Valencià', 'language.english': 'English', 'language.label': 'Idioma',
    'nav.home': 'Inici', 'nav.members': 'Associats', 'nav.data': 'Dades', 'nav.calendar': 'Calendari', 'nav.registrations': 'Inscripcions', 'nav.forms': 'Formularis', 'nav.exercises': 'Exercicis', 'nav.record': 'Registre', 'nav.requests': 'Sol·licituds', 'nav.permissions': 'Permisos',
    'common.support': 'Suport', 'common.adminSupport': 'Suport administratiu', 'common.logout': 'Eixir', 'common.close': 'Tancar', 'common.cancel': 'Cancel·lar', 'common.loading': 'Carregant...',
    'login.accessAssociations': 'Accés associacions', 'login.title': 'Secretaria FFSJ', 'login.subtitle': 'Accés per a fogueres i barraques.', 'login.help': 'Entra amb el CIF de la teua associació i la contrasenya facilitada per Secretaria.', 'login.identification': 'Identificació', 'login.enterAssociation': 'Entrar com a associació', 'login.credentialsHelp': 'Utilitza les credencials de l’entitat, no les d’una persona concreta.', 'login.cif': 'CIF de l’associació', 'login.cifPlaceholder': 'Ex. F00000000', 'login.password': 'Contrasenya', 'login.entering': 'Entrant...', 'login.forgot': 'No recorde la contrasenya', 'login.required': 'Introdueix el CIF de l’associació i la contrasenya.', 'login.failed': 'No s’ha pogut iniciar sessió. Revisa el CIF i la contrasenya.',
    'attachments.select': 'Adjuntar arxiu', 'attachments.selected': 'Arxius seleccionats', 'login.adminAccess': 'Soc personal d’administració'
    ,'rubi.open': 'Obrir Rubi, assistent virtual', 'rubi.close': 'Tancar Rubi', 'rubi.name': 'Rubi', 'rubi.you': 'Tu', 'rubi.status': 'Estat', 'rubi.subtitle': 'El teu assistent virtual de Secretaria FFSJ', 'rubi.welcome': 'Hola, soc Rubi, el teu assistent virtual de Secretaria FFSJ. En que et puc ajudar?', 'rubi.quickActions': 'Consultes frequents', 'rubi.quick.alta': "Donar d'alta una persona", 'rubi.quick.documents': 'Enviar documentacio', 'rubi.quick.inscriptions': "Inscriure'm en una activitat", 'rubi.quick.support': 'Tinc un problema', 'rubi.inputLabel': 'Escriu la teua consulta a Rubi', 'rubi.placeholder': 'Escriu la teua consulta...', 'rubi.send': 'Enviar', 'rubi.loading': 'Rubi esta preparant una resposta...', 'rubi.disabled': 'Rubi no esta disponible en aquest moment.', 'rubi.error.auth': 'La teua sessio no permet usar Rubi. Torna a iniciar sessio.', 'rubi.error.limit': 'Has arribat al limit temporal de consultes. Torna-ho a intentar en uns minuts.', 'rubi.error.disabled': 'Rubi esta deshabilitada temporalment.', 'rubi.error.unavailable': 'Rubi no esta disponible temporalment. Torna-ho a intentar mes tard.', 'rubi.error.timeout': 'Rubi ha tardat massa a respondre. Pots tornar-ho a intentar.', 'rubi.error.invalid': 'No hem pogut processar la resposta de Rubi. Pots tornar-ho a intentar.', 'rubi.action.personas': 'Anar a Persones', 'rubi.action.registro': 'Anar a Registre', 'rubi.action.inscripciones': 'Obrir Inscripcions', 'rubi.action.soporte': 'Obrir Suport', 'rubi.action.calendario': 'Obrir Calendari', 'rubi.action.solicitudes': 'Anar a Sollicituds', 'rubi.action.alta': 'Obrir alta de persona'
  },
  en: {
    'language.spanish': 'Spanish', 'language.valencian': 'Valencian', 'language.english': 'English', 'language.label': 'Language',
    'nav.home': 'Home', 'nav.members': 'Members', 'nav.data': 'Details', 'nav.calendar': 'Calendar', 'nav.registrations': 'Registrations', 'nav.forms': 'Forms', 'nav.exercises': 'Financial years', 'nav.record': 'Records', 'nav.requests': 'Requests', 'nav.permissions': 'Permissions',
    'common.support': 'Support', 'common.adminSupport': 'Administrative support', 'common.logout': 'Sign out', 'common.close': 'Close', 'common.cancel': 'Cancel', 'common.loading': 'Loading...',
    'login.accessAssociations': 'Association access', 'login.title': 'FFSJ Secretariat', 'login.subtitle': 'Access for bonfire and barraca groups.', 'login.help': 'Sign in with your association CIF and the password supplied by the Secretariat.', 'login.identification': 'Identification', 'login.enterAssociation': 'Sign in as an association', 'login.credentialsHelp': 'Use the organisation credentials, not those of an individual.', 'login.cif': 'Association CIF', 'login.cifPlaceholder': 'E.g. F00000000', 'login.password': 'Password', 'login.entering': 'Signing in...', 'login.forgot': 'I do not remember my password', 'login.required': 'Enter the association CIF and password.', 'login.failed': 'We could not sign you in. Check the CIF and password.',
    'attachments.select': 'Attach file', 'attachments.selected': 'Selected files', 'login.adminAccess': 'I am administrative staff'
    ,'rubi.open': 'Open Rubi, virtual assistant', 'rubi.close': 'Close Rubi', 'rubi.name': 'Rubi', 'rubi.you': 'You', 'rubi.status': 'Status', 'rubi.subtitle': 'Your FFSJ Secretariat virtual assistant', 'rubi.welcome': 'Hello! I am Rubi, your FFSJ Secretariat virtual assistant. How can I help you?', 'rubi.quickActions': 'Common requests', 'rubi.quick.alta': 'Register a person', 'rubi.quick.documents': 'Send documentation', 'rubi.quick.inscriptions': 'Register for an activity', 'rubi.quick.support': 'I have a problem', 'rubi.inputLabel': 'Write your question for Rubi', 'rubi.placeholder': 'Write your question...', 'rubi.send': 'Send', 'rubi.loading': 'Rubi is preparing an answer...', 'rubi.disabled': 'Rubi is not available at the moment.', 'rubi.error.auth': 'Your session cannot use Rubi. Please sign in again.', 'rubi.error.limit': 'You have reached the temporary question limit. Try again in a few minutes.', 'rubi.error.disabled': 'Rubi is temporarily disabled.', 'rubi.error.unavailable': 'Rubi is temporarily unavailable. Please try again later.', 'rubi.error.timeout': 'Rubi took too long to answer. You can try again.', 'rubi.error.invalid': 'We could not process Rubi response. You can try again.', 'rubi.action.personas': 'Go to People', 'rubi.action.registro': 'Go to Records', 'rubi.action.inscripciones': 'Open Registrations', 'rubi.action.soporte': 'Open Support', 'rubi.action.calendario': 'Open Calendar', 'rubi.action.solicitudes': 'Go to Requests', 'rubi.action.alta': 'Open person registration'
  }
};

@Injectable({ providedIn: 'root' })
export class I18nService {
  private readonly storageKey = 'ffsj-secretaria.language';
  private readonly languageSubject = new BehaviorSubject<AppLanguage>(this.initialLanguage());
  readonly languageChanges = this.languageSubject.asObservable();
  get language(): AppLanguage { return this.languageSubject.value; }
  setLanguage(language: AppLanguage): void { localStorage.setItem(this.storageKey, language); this.languageSubject.next(language); }
  t(key: string): string {
    const translated = translations[this.language][key] || translations.es[key];
    if (translated) return translated;
    // A missing catalogue entry must never render as an implementation key.
    return key.split('.').pop()?.replace(/([a-z])([A-Z])/g, '$1 $2') || '—';
  }
  private initialLanguage(): AppLanguage { const saved = localStorage.getItem(this.storageKey); return saved === 'va' || saved === 'en' || saved === 'es' ? saved : 'es'; }
}
